name: event_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter # Thêm dòng này để khai báo gói `flutter_localizations`
  intl: any
  localstore: ^1.4.0
  syncfusion_flutter_calendar: ^27.1.58

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0 # Thêm dòng này để khai báo build_runner

flutter:
  uses-material-design: true
  generate: true # Thêm dòng này để bật cờ generate
